name: Main build
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Package with Maven (skip tests)
      - name: Package with Maven
        run: mvn package -DskipTests

      # Unit test (will not fail if no tests are found)
      - name: Unit test
        run: mvn test -DfailIfNoTests=false || true

      # Build and run Docker Compose
      - name: Build and Run Docker Compose
        run: |
          docker compose up --abort-on-container-exit

      # View logs from the running container
      - name: View logs
        run: docker logs devopscontainer

      # Optionally, you can remove the container after logs
      - name: Clean up Docker container
        run: docker compose down
