name: Main build
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Testing
        run: mvn -Dtest=com.napier.devops.AppTest test
      - name: Build Docker Image
      run: |
      mvn package -DskipTests
      docker compose up --abort-on-container-ex
      - name: view logs
        run: docker logs devopscontainer

