name: A workflow for my App
on: push

jobs:
  build:
    name: Test Build Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests (with no tests present)
        run: mvn test -DskipTests=true

      - name: Package and Run Docker Compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit

      - name: View Logs
        run: docker logs devops-app-1

      - name: Copy Output
        run: docker container cp devops-app-1:/tmp/output ./

      - name: List Directories
        run: |
          pwd
          ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
